[project]
name = "lecture-20251101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kafka-python>=2.2.15",
    "pika>=1.3.2",
    "valkey>=6.1.1",
]
